### ISSUE TITLE
Comparison with rooted stock firmware a9?

### ISSUE THREAD

**Issue by m1ndy** [damianmqr/a9_accessibility_service#5]
Thank you for putting this together and sharing openly!

I'm curious, in your daily use, do you find this to be strictly a superior experience compared to rooting the stock firmware?
So, now the comparison is between:
1. This repo's LineageOS + your eink features patch
2. Stock firmware + rooting to enable GApps

Is there any compromise you make when choosing #1? Anything that #2 has that #1 does not?

**Comment by damianmqr** [comment]
It's a new project and I'm still trying to work out what that list of differences may be myself.

But from using it for the past few days I'd say there are certainly some advantages of using a patched LOS
1. Google apps are more easily accessible (and in my experience work better than simply installing GApps via Magisk)
2. The stock bloatware apps are removed, many of which phoned home from time to time and weren't straightforward to find and remove even with root.
3. You can easily use LOS without root
4. You get features of the newest Android 14! (I believe stock is at 11)

There are still things stock OS does better obviously, it was developed with that phone in mind.
A lot of elements there have a theme that works really well with e-ink whereas on Lineage even when you change the launcher there are areas which aren't optimized for e-ink.
On top of that there are occasional hardware issues I'm trying to look into, for example OTG cable doesn't seem to work with LineageOS.

I'm planning to dailydrive this and address the problems that come up as I go, but so far I've enjoyed both working on this project and using it as my main device.
